### ISSUE TITLE
Setup a discord channel for developers

### ISSUE THREAD

**Issue by naveedh-dantechain** [uniVocity/univocity-trader#102]
Please setup a discord channel where developers can interact and discuss more needed features. I can help managing the discord channel.

**Comment by jbax** [comment]
Thanks for the suggestion but I'm opposed to having features discussed in a space that's not open to everyone and requires yet another social media for everyone to worry about. I also have zero time available to keep chatting about this stuff and following that.

If anyone wants to suggest a feature, please just open an issue here on github to discuss that feature in particular. Discord and message boards are way too messy to organize this sort of stuff.
