### ISSUE TITLE
Buy/Sell signal with amount?

### ISSUE THREAD

**Issue by brkr** [uniVocity/univocity-trader#21]
First of all i love this project. Great work! (and sorry for my English! )

I need to buy/sell signal with amount. For example,

My Strategy : 
    Price 1000$ -> Buy  100 (amount)
    if Price down 900$ -> Buy 200 (amount)
 
My target is reduce my avarage cost.

Is there any way achieve this strategy?

**Comment by jbax** [comment]
You can to provide your own implementation of the [OrderManager](https://github.com/uniVocity/univocity-trader/blob/b4814f5f7c0a83061d826eebd86b33d6fcb38bf6/univocity-trader-core/src/main/java/com/univocity/trader/account/OrderManager.java) interface, implement your login on the `prepareOrder` method to define what is the amount to buy/sell.

To allow for buying multiple times right now, comment out [this condition](https://github.com/uniVocity/univocity-trader/blob/a583da037be25f761799261415b5c1b3c19c49e2/univocity-trader-core/src/main/java/com/univocity/trader/account/Trader.java#L220). I'm going to make changes to how trades are processed later on to properly handle multiple buy orders on the same asset, so I'm leaving this issue open until this is ready.

Thanks a lot for using our project.

**Comment by jbax** [comment]
Ok so I made the bulk of the changes required to submit orders independently and even implemented the [MartingaleSimulation](https://github.com/uniVocity/univocity-trader/blob/master/univocity-trader-examples/src/main/java/com/univocity/trader/examples/MartingaleSimulation.java) which kind of does what you describe (basically doubles the position if lost a given percentage). The bulk of the logic for that to work is in the [MartingaleStrategyMonitor](https://github.com/uniVocity/univocity-trader/blob/master/univocity-trader-examples/src/main/java/com/univocity/trader/examples/MartingaleStrategyMonitor.java).

Use this as a reference only. Don't try with real money as you will probably lose even though the simulation doesn't.

**Comment by brkr** [comment]
Great work! Thank you!
