### ISSUE TITLE
Loading currently open positions and overriding method

### ISSUE THREAD

**Issue by kpchand** [uniVocity/univocity-trader#30]
Is there a way to load currently open positions preferabbly as a separate object?

The method which loads the positions can be made overridable so if we have multiple strategies running on one account, and say 2 strategies have positions on asset X with quantity 10 and 20 each then we can determine what is the position for the current strategy in asset X by subtracting the total open position on the asset X in our account by a value we stored locally. 

The value could have been saved in the last run of our current strategy when it received fill status.

So this way we know that even though the account has 30 shares of X, we have to only see it as 10(30 - 20) if we are inside the second strategy.

**Comment by jbax** [comment]
I'm not 100% clear on what you need. Could you provide some sample code
illustrating what you'd like to do?

I believe what you need can be extracted from each individual Trade object
inside the Trader. They store the strategy and the orders.

**Comment by jbax** [comment]
When live trading, [ClientAccount.updateBalances()](https://github.com/uniVocity/univocity-trader/blob/master/univocity-trader-core/src/main/java/com/univocity/trader/ClientAccount.java#L63) should return a `Map<String, Balance>` with all open positions, including amounts locked (i.e. in some order). Even if you open a trade manually on the exchange directly, `updateBalances` will pick up the changes in your account balance.

This is done atuomatically and you can simply use `Balance balance = trader.balance("BTC")` from within the `OrderManager` that is called before (and after) placing an order.

Let me know if this helps

**Comment by kpchand** [comment]
Looks like it is what I was looking for. Thanks.
