### ISSUE TITLE
OrderExecutionLine strips away original data types

### ISSUE THREAD

**Issue by wwadge** [uniVocity/univocity-trader#40]
OrderExecutionLine should maintain the original data types because it currently assumes a text-based output. For the output to Google Sheets, it helps to transmit the actual types so that the sheet values are formatted correctly.

I've done the required modifications( here: https://github.com/wwadge/univocity-trader-1/tree/feature/fix-google-logging-types) but this works by exposing a getFormattedXXX in to keep the existing String-based formatting.

Is there a way to to tell CSV parser to tell it that field X should call getFormattedX() instead of getting the field value?

**Comment by jbax** [comment]
Move the @Parsed annotation to the getFornattedX() methods and set the
original column name in the annotation.

**Comment by wwadge** [comment]
Fixed here: https://github.com/uniVocity/univocity-trader/pull/41

**Comment by jbax** [comment]
PR merged, thanks a lot for your contribution once again.
